In [1]:
import pandas as pd
import warnings
import numpy as np
warnings.filterwarnings('ignore')
import json
import ast

In [25]:
credits_csv = pd.read_csv('../datasets/credits.csv')
credits_df = credits_csv.copy()

In [27]:
credits_df.loc[credits_df.id == 9312]

,cast,crew,id
43,"[{'cast_id': 1, 'character': 'Lord Rayden', 'c...","[{'credit_id': '52fe44e6c3a36847f80b0899', 'de...",9312

Creo un dataframe con toda la data limpia y organizada por pelicula

In [28]:
cast_crew_df = pd.DataFrame()

- id_movie
- cast_id

Creo nuevas columnas para alojar los datos de la columna 'cast'

In [180]:
import json

for index, value in enumerate(credits_df.cast[:10]):
    #new_columns = ['cast_id', 'character', 'credit_id', 'gender', 'id', 'name', 'order', 'profile_path']
    cast_id = []
    character = []
    credit_id = []
    gender = []
    id_ = []
    name = []
    order = []
    profile_path = []
    
    value = value.strip('[]')
    lista = value.split('}, {')
    for dicc in lista:
        dicc = dicc.replace('{', '').replace('}', '').replace('"', '').replace("None","'None'")
        dicc = '{' + dicc + '}'
        dicc = dicc.replace("'", '"')
        try:
            real_dict = json.loads(dicc)
            print(real_dict)
        except json.JSONDecodeError as e:
            pass
        cast_id.append(real_dict['cast_id'])
        character.append(real_dict['character'])
        credit_id.append(real_dict['credit_id'])
        gender.append(real_dict['gender'])
        id_.append(real_dict['id'])
        name.append(real_dict['name'])
        order.append(real_dict['order'])
        profile_path.append(real_dict['profile_path'])

    credits_df.at[index,'cast_id'] = str(cast_id)
    credits_df.at[index,'character'] = str(character)
    credits_df.at[index,'credit_id'] = str(credit_id)
    credits_df.at[index,'gender'] = str(gender)
    credits_df.at[index,'id'] = str(id_)
    credits_df.at[index,'name'] = str(name)
    credits_df.at[index,'order'] = str(order)
    credits_df.at[index,'profile_path'] = str(profile_path)

{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}
{'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}
{'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}
{'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}
{'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}
{'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}
{'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}
{'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}
{'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}
{'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}
{'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}
{'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': 'None'}
{'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}
{'cast_id': 1, 'character': 'Alan Parrish', 'credit_id': '52fe44bfc3a36847f80a7c73', 'gender': 2, 'id': 2157, 'name': 'Robin Williams', 'order': 0, 'profile_path': '/sojtJyIV3lkUeThD7A2oHNm8183.jpg'}
{'cast_id': 8, 'character': 'Samuel Alan Parrish / Van Pelt', 'credit_id': '52fe44bfc3a36847f80a7c99', 'gender': 2, 'id': 8537, 'name': 'Jonathan Hyde', 'order': 1, 'profile_path': '/7il5D76vx6QVRVlpVvBPEC40MBi.jpg'}
{'cast_id': 2, 'character': 'Judy Sheperd', 'credit_id': '52fe44bfc3a36847f80a7c77', 'gender': 1, 'id': 205, 'name': 'Kirsten Dunst', 'order': 2, 'profile_path': '/wBXvh6PJd0IUVNpvatPC1kzuHtm.jpg'}
{'cast_id': 24, 'character': 'Peter Shepherd', 'credit_id': '52fe44c0c3a36847f80a7ce7', 'gender': 0, 'id': 145151, 'name': 'Bradley Pierce', 'order': 3, 'profile_path': '/j6iW0vVA23GQniAPSYI6mi4hiEW.jpg'}
{'cast_id': 10, 'character': 'Sarah Whittle', 'credit_id': '52fe44bfc3a36847f80a7c9d', 'gender': 1, 'id': 5149, 'name': 'Bonnie Hunt', 'order': 4, 'profile_path': '/7spiVQwmr8siw5QCcvvdRG3c7Lf.jpg'}
{'cast_id': 25, 'character': 'Nora Shepherd', 'credit_id': '52fe44c0c3a36847f80a7ceb', 'gender': 1, 'id': 10739, 'name': 'Bebe Neuwirth', 'order': 5, 'profile_path': '/xm58rpMRVDHS0IGttw1pTlqGwkN.jpg'}
{'cast_id': 26, 'character': 'Carl Bentley', 'credit_id': '52fe44c0c3a36847f80a7cef', 'gender': 2, 'id': 58563, 'name': 'David Alan Grier', 'order': 6, 'profile_path': '/5tkt3qRZTco4sz604aTIarQ0m8W.jpg'}
{'cast_id': 11, 'character': 'Carol Anne Parrish', 'credit_id': '52fe44bfc3a36847f80a7ca1', 'gender': 1, 'id': 1276, 'name': 'Patricia Clarkson', 'order': 7, 'profile_path': '/10ZSyaUqzUlKTd60HmeiGhlytZG.jpg'}
{'cast_id': 14, 'character': 'Alan Parrish (young)', 'credit_id': '52fe44bfc3a36847f80a7cad', 'gender': 0, 'id': 46530, 'name': 'Adam Hann-Byrd', 'order': 8, 'profile_path': '/hEoqDqtMO91hYWD5iDrDesnLDlt.jpg'}
{'cast_id': 13, 'character': 'Sarah Whittle (young)', 'credit_id': '52fe44bfc3a36847f80a7ca9', 'gender': 1, 'id': 56523, 'name': 'Laura Bell Bundy', 'order': 9, 'profile_path': '/8tAVDBRoZPjKfCbBDyh4iK9JNEp.jpg'}
{'cast_id': 31, 'character': 'Exterminator', 'credit_id': '52fe44c0c3a36847f80a7cff', 'gender': 2, 'id': 51551, 'name': 'James Handy', 'order': 10, 'profile_path': '/vm0WQmuP8jEGgFTd3VCcJe7zpUi.jpg'}
{'cast_id': 12, 'character': 'Mrs. Thomas the Realtor', 'credit_id': '52fe44bfc3a36847f80a7ca5', 'gender': 1, 'id': 56522, 'name': 'Gillian Barber', 'order': 11, 'profile_path': '/qoqPX15J5jh6Sy0A9JvvRJIuw64.jpg'}
{'cast_id': 28, 'character': 'Benjamin', 'credit_id': '52fe44c0c3a36847f80a7cf3', 'gender': 2, 'id': 1000304, 'name': 'Brandon Obray', 'order': 12, 'profile_path': 'None'}
{'cast_id': 29, 'character': 'Caleb', 'credit_id': '52fe44c0c3a36847f80a7cf7', 'gender': 0, 'id': 188949, 'name': 'Cyrus Thiedeke', 'order': 13, 'profile_path': 'None'}
{'cast_id': 30, 'character': 'Billy Jessup', 'credit_id': '52fe44c0c3a36847f80a7cfb', 'gender': 0, 'id': 1076551, 'name': 'Gary Joseph Thorup', 'order': 14, 'profile_path': 'None'}
{'cast_id': 32, 'character': 'Cop', 'credit_id': '5588053fc3a36838530063f5', 'gender': 0, 'id': 1480246, 'name': 'Leonard Zola', 'order': 15, 'profile_path': 'None'}
{'cast_id': 33, 'character': 'Bum', 'credit_id': '55935687925141645a002097', 'gender': 2, 'id': 25024, 'name': 'Lloyd Berry', 'order': 16, 'profile_path': '/s7SVCOtvcuQ9wRQPZfUdahb5x88.jpg'}
{'cast_id': 34, 'character': 'Jim Shepherd', 'credit_id': '559356d09251415df8002cb7', 'gender': 2, 'id': 27110, 'name': 'Malcolm Stewart', 'order': 17, 'profile_path': '/l2vgzkLR7GRr8ugjZCILA0OiliI.jpg'}
{'cast_id': 35, 'character': 'Martha Shepherd', 'credit_id': '55935730925141645a0020ad', 'gender': 0, 'id': 53715, 'name': 'Annabel Kershaw', 'order': 18, 'profile_path': '/1VqbvAohBwFhETZtDe76JXQcxKm.jpg'}
{'cast_id': 36, 'character': 'Gun Salesman', 'credit_id': '5593576992514167fd000610', 'gender': 2, 'id': 1379424, 'name': 'Darryl Henriques', 'order': 19, 'profile_path': '/7QMHooY9ewNQlE24WKAOdwW0evU.jpg'}
{'cast_id': 37, 'character': 'Paramedic', 'credit_id': '559357ae92514152de002f42', 'gender': 0, 'id': 1235504, 'name': 'Robyn Driscoll', 'order': 20, 'profile_path': 'None'}
{'cast_id': 50, 'character': 'Paramedic', 'credit_id': '5657803b925141018f00a5dc', 'gender': 2, 'id': 25389, 'name': 'Peter Bryant', 'order': 21, 'profile_path': '/fkcx9Tnp25UC5HlI2eW3nGvumsZ.jpg'}
{'cast_id': 39, 'character': 'Girl', 'credit_id': '559358e292514152de002f63', 'gender': 0, 'id': 1483449, 'name': 'Sarah Gilson', 'order': 22, 'profile_path': 'None'}
{'cast_id': 40, 'character': 'Girl', 'credit_id': '5593590d92514152db002df3', 'gender': 0, 'id': 1483450, 'name': 'Florica Vlad', 'order': 23, 'profile_path': 'None'}
{'cast_id': 41, 'character': 'Baker', 'credit_id': '55935946c3a36869d1001b4d', 'gender': 0, 'id': 1483451, 'name': 'June Lion', 'order': 24, 'profile_path': 'None'}
{'cast_id': 42, 'character': 'Pianist', 'credit_id': '5593597692514167fd000644', 'gender': 0, 'id': 1483452, 'name': 'Brenda Lockmuller', 'order': 25, 'profile_path': 'None'}
{'cast_id': 2, 'character': 'Max Goldman', 'credit_id': '52fe466a9251416c75077a8d', 'gender': 2, 'id': 6837, 'name': 'Walter Matthau', 'order': 0, 'profile_path': '/xJVkvprOnzP5Zdh5y63y8HHniDZ.jpg'}
{'cast_id': 3, 'character': 'John Gustafson', 'credit_id': '52fe466a9251416c75077a91', 'gender': 2, 'id': 3151, 'name': 'Jack Lemmon', 'order': 1, 'profile_path': '/chZmNRYMtqkiDlatprGDH4BzGqG.jpg'}
{'cast_id': 4, 'character': 'Ariel Gustafson', 'credit_id': '52fe466a9251416c75077a95', 'gender': 1, 'id': 13567, 'name': 'Ann-Margret', 'order': 2, 'profile_path': '/jx5lTaJ5VXZHYB52gaOTAZ9STZk.jpg'}
{'cast_id': 5, 'character': 'Maria Sophia Coletta Ragetti', 'credit_id': '52fe466a9251416c75077a99', 'gender': 1, 'id': 16757, 'name': 'Sophia Loren', 'order': 3, 'profile_path': '/emKLhbji1c7BjcA2DdbWf0EP9zH.jpg'}
{'cast_id': 6, 'character': 'Melanie Gustafson', 'credit_id': '52fe466a9251416c75077a9d', 'gender': 1, 'id': 589, 'name': 'Daryl Hannah', 'order': 4, 'profile_path': '/4LLmp6AQdlj6ueGCRbVRSGvvFSt.jpg'}
{'cast_id': 9, 'character': 'Grandpa Gustafson', 'credit_id': '53e5fcc2c3a3684430000d65', 'gender': 2, 'id': 16523, 'name': 'Burgess Meredith', 'order': 5, 'profile_path': '/lm98oKloU33Q7QDIIMSyc4Pr2jA.jpg'}
{'cast_id': 10, 'character': 'Jacob Goldman', 'credit_id': '53e5fcd4c3a3684433000e1a', 'gender': 2, 'id': 7166, 'name': 'Kevin Pollak', 'order': 6, 'profile_path': '/kwu2T8CDnThZTzE88uiSgJ5eHXf.jpg'}
{'cast_id': 4, 'character': 'Robin Stokes', 'credit_id': '52fe44779251416c91011ab9', 'gender': 1, 'id': 51359, 'name': 'Lela Rochon', 'order': 3, 'profile_path': '/9DBu3r5O4fBosSS4FnSzFCVpm0O.jpg'}
{'cast_id': 5, 'character': 'Marvin King', 'credit_id': '52fe44779251416c91011abd', 'gender': 2, 'id': 66804, 'name': 'Gregory Hines', 'order': 4, 'profile_path': '/rvvQWFQGeGR14WFVNe0Qg1J7uVY.jpg'}
{'cast_id': 6, 'character': 'Kenneth Dawkins', 'credit_id': '52fe44779251416c91011ac1', 'gender': 2, 'id': 352, 'name': 'Dennis Haysbert', 'order': 5, 'profile_path': '/mn5Nc5Q31GslpVVWs8p41W4TBma.jpg'}
{'cast_id': 8, 'character': 'John Harris, Sr.', 'credit_id': '52fe44779251416c91011ac5', 'gender': 2, 'id': 87118, 'name': 'Michael Beach', 'order': 6, 'profile_path': '/lOlWhURNKyZHn71dvq7qC7fiwN6.jpg'}
{'cast_id': 10, 'character': 'Troy', 'credit_id': '52fe44779251416c91011acf', 'gender': 2, 'id': 34, 'name': 'Mykelti Williamson', 'order': 7, 'profile_path': '/8TTxzpuvvpw2tB8xZBCDslYupNU.jpg'}
{'cast_id': 20, 'character': 'Joseph', 'credit_id': '56d1b15fc3a3681e4a008b6b', 'gender': 2, 'id': 1276777, 'name': 'Lamont Johnson', 'order': 8, 'profile_path': '/wfZzRPJBdsx62GbkUimc1PShxyC.jpg'}
{'cast_id': 21, 'character': 'James Wheeler', 'credit_id': '56f8a929c3a36816e80084f3', 'gender': 2, 'id': 10814, 'name': 'Wesley Snipes', 'order': 9, 'profile_path': '/hQ6EBa6vgu7HoZpzms8Y10VL5Iw.jpg'}
{'cast_id': 1, 'character': 'George Banks', 'credit_id': '52fe44959251416c75039eb9', 'gender': 2, 'id': 67773, 'name': 'Steve Martin', 'order': 0, 'profile_path': '/rI2EMvkfKKPKa5z0nM2pFVBtUyO.jpg'}
{'cast_id': 2, 'character': 'Nina Banks', 'credit_id': '52fe44959251416c75039ebd', 'gender': 1, 'id': 3092, 'name': 'Diane Keaton', 'order': 1, 'profile_path': '/fzgUMnbOkxC6E3EFcYHWHFaiKyp.jpg'}
{'cast_id': 3, 'character': 'Franck Eggelhoffer', 'credit_id': '52fe44959251416c75039ec1', 'gender': 2, 'id': 519, 'name': 'Martin Short', 'order': 2, 'profile_path': '/oZQorXBjTxrdkTJFpoDwOcQ91ji.jpg'}
{'cast_id': 4, 'character': 'Annie Banks-MacKenzie', 'credit_id': '52fe44959251416c75039ec5', 'gender': 1, 'id': 70696, 'name': 'Kimberly Williams-Paisley', 'order': 3, 'profile_path': '/nVp4F4VFqVvjh6huOULUQoiAguY.jpg'}
{'cast_id': 13, 'character': 'Bryan MacKenzie', 'credit_id': '52fe44959251416c75039ef3', 'gender': 2, 'id': 59222, 'name': 'George Newbern', 'order': 4, 'profile_path': '/48Ouqe1g8QrZ6qjvap5NvhfKuly.jpg'}
{'cast_id': 14, 'character': 'Matty Banks', 'credit_id': '52fe44959251416c75039ef7', 'gender': 0, 'id': 18793, 'name': 'Kieran Culkin', 'order': 5, 'profile_path': '/swcqQCMREeGCk6FAxIfczGpFBys.jpg'}
{'cast_id': 15, 'character': 'Howard Weinstein', 'credit_id': '52fe44959251416c75039efb', 'gender': 2, 'id': 14592, 'name': 'BD Wong', 'order': 6, 'profile_path': '/o8JUV37KWNorHOabp3zyD756oE3.jpg'}
{'cast_id': 16, 'character': 'John MacKenzie', 'credit_id': '52fe44959251416c75039eff', 'gender': 2, 'id': 20906, 'name': 'Peter Michael Goetz', 'order': 7, 'profile_path': '/a2hLcCidETgwlVyQnYy4kXVKUcn.jpg'}
{'cast_id': 17, 'character': 'Joanna MacKenzie', 'credit_id': '52fe44959251416c75039f03', 'gender': 1, 'id': 54348, 'name': 'Kate McGregor-Stewart', 'order': 8, 'profile_path': '/vsvdAmMZgX85AvnVFd4jigOUipZ.jpg'}
{'cast_id': 18, 'character': 'Dr. Megan Eisenberg', 'credit_id': '52fe44959251416c75039f07', 'gender': 1, 'id': 209, 'name': 'Jane Adams', 'order': 9, 'profile_path': '/HbQfL01xmV1psnh0WvldIBzDg3.jpg'}
{'cast_id': 19, 'character': 'Mr. Habib', 'credit_id': '52fe44959251416c75039f0b', 'gender': 2, 'id': 26510, 'name': 'Eugene Levy', 'order': 10, 'profile_path': '/69IBiDjU1gSqtrcGOA7PA7aEYsc.jpg'}
{'cast_id': 20, 'character': 'Wife Mrs. Habib', 'credit_id': '57ffa654c3a3681552000277', 'gender': 1, 'id': 24358, 'name': 'Lori Alan', 'order': 11, 'profile_path': '/mNfJWzuaKgkIaK7CuirXOMosd2h.jpg'}
{'cast_id': 25, 'character': 'Lt. Vincent Hanna', 'credit_id': '52fe4292c3a36847f80291f5', 'gender': 2, 'id': 1158, 'name': 'Al Pacino', 'order': 0, 'profile_path': '/ks7Ba8x9fJUlP9decBr6Dh5mThX.jpg'}
{'cast_id': 26, 'character': 'Neil McCauley', 'credit_id': '52fe4292c3a36847f80291f9', 'gender': 2, 'id': 380, 'name': 'Robert De Niro', 'order': 1, 'profile_path': '/lvTSwUcvJRLAJ2FB5qFaukel516.jpg'}
{'cast_id': 27, 'character': 'Chris Shiherlis', 'credit_id': '52fe4292c3a36847f80291fd', 'gender': 2, 'id': 5576, 'name': 'Val Kilmer', 'order': 2, 'profile_path': '/AlhPeiH8R4reMNGNQ9ag1FPbuW9.jpg'}
{'cast_id': 28, 'character': 'Nate', 'credit_id': '52fe4292c3a36847f8029201', 'gender': 2, 'id': 10127, 'name': 'Jon Voight', 'order': 3, 'profile_path': '/c7BvyqlvqDkfkFqSBUCiR21fvTh.jpg'}
{'cast_id': 29, 'character': 'Michael Cheritto', 'credit_id': '52fe4292c3a36847f8029205', 'gender': 2, 'id': 3197, 'name': 'Tom Sizemore', 'order': 4, 'profile_path': '/soINOuacuiThRb2LyPD4tTWve7C.jpg'}
{'cast_id': 30, 'character': 'Justine Hanna', 'credit_id': '52fe4292c3a36847f8029209', 'gender': 1, 'id': 6200, 'name': 'Diane Venora', 'order': 5, 'profile_path': '/3k7w5Y7gTAxN1JML7jhN8F8rVrS.jpg'}
{'cast_id': 31, 'character': 'Eady', 'credit_id': '52fe4292c3a36847f802920d', 'gender': 1, 'id': 15851, 'name': 'Amy Brenneman', 'order': 6, 'profile_path': '/xC408loYq7tQlkpS5YH68SoaDND.jpg'}
{'cast_id': 32, 'character': 'Charlene Shiherlis', 'credit_id': '52fe4292c3a36847f8029211', 'gender': 1, 'id': 15852, 'name': 'Ashley Judd', 'order': 7, 'profile_path': '/3bgmRDt02iGFVjhqCqstVyEeiwG.jpg'}
{'cast_id': 33, 'character': 'Sergeant Drucker', 'credit_id': '52fe4292c3a36847f8029215', 'gender': 2, 'id': 34, 'name': 'Mykelti Williamson', 'order': 8, 'profile_path': '/8TTxzpuvvpw2tB8xZBCDslYupNU.jpg'}
{'cast_id': 38, 'character': 'Lauren Gustafson', 'credit_id': '52fe4292c3a36847f8029229', 'gender': 1, 'id': 524, 'name': 'Natalie Portman', 'order': 9, 'profile_path': '/1oEP6OyYZgyLubgJXifx2GO78c7.jpg'}
{'cast_id': 35, 'character': 'Bosko', 'credit_id': '52fe4292c3a36847f802921d', 'gender': 2, 'id': 15854, 'name': 'Ted Levine', 'order': 10, 'profile_path': '/7O3vgqgicfNeGr3leC0qB074fjX.jpg'}
{'cast_id': 39, 'character': 'Kelso', 'credit_id': '52fe4292c3a36847f802922d', 'gender': 2, 'id': 119232, 'name': 'Tom Noonan', 'order': 11, 'profile_path': '/cpINV4Q8IeVgSLyKz9ldzzAGr5n.jpg'}
{'cast_id': 41, 'character': 'Richard Torena', 'credit_id': '52fe4292c3a36847f8029237', 'gender': 2, 'id': 31004, 'name': 'Tone Loc', 'order': 12, 'profile_path': '/o940ZhEYQYrOJdhRnmPrYoc9iOq.jpg'}
{'cast_id': 42, 'character': 'Alan Marciano', 'credit_id': '52fe4292c3a36847f802923b', 'gender': 2, 'id': 5587, 'name': 'Hank Azaria', 'order': 13, 'profile_path': '/3vIdbP73nKnKpMAcgGWoALPF2JO.jpg'}
{'cast_id': 34, 'character': 'Detective Casals', 'credit_id': '52fe4292c3a36847f8029219', 'gender': 2, 'id': 15853, 'name': 'Wes Studi', 'order': 14, 'profile_path': '/2b1hfAOoVjU7HoSbyHzGjl8DWs1.jpg'}
{'cast_id': 36, 'character': 'Donald Breedan', 'credit_id': '52fe4292c3a36847f8029221', 'gender': 2, 'id': 352, 'name': 'Dennis Haysbert', 'order': 15, 'profile_path': '/mn5Nc5Q31GslpVVWs8p41W4TBma.jpg'}
{'cast_id': 46, 'character': 'Trejo', 'credit_id': '52fe4292c3a36847f802924b', 'gender': 2, 'id': 11160, 'name': 'Danny Trejo', 'order': 16, 'profile_path': '/7b8cDfrmeheQbgryfCm7MeJOxxM.jpg'}
{'cast_id': 47, 'character': 'Hugh Benny', 'credit_id': '52fe4292c3a36847f802924f', 'gender': 2, 'id': 9290, 'name': 'Henry Rollins', 'order': 17, 'profile_path': '/2E0cZdoJsdt1Lv4waG3s6fsfJeU.jpg'}
{'cast_id': 37, 'character': 'Roger Van Zant', 'credit_id': '52fe4292c3a36847f8029225', 'gender': 2, 'id': 886, 'name': 'William Fichtner', 'order': 18, 'profile_path': '/apj1bgzZI2efSdJolfp6KjhG8CF.jpg'}
{'cast_id': 43, 'character': 'Waingro', 'credit_id': '52fe4292c3a36847f802923f', 'gender': 2, 'id': 34839, 'name': 'Kevin Gage', 'order': 19, 'profile_path': '/egIApa0PPsHkAwrGnOAUtdqO6CQ.jpg'}
{'cast_id': 44, 'character': 'Elaine Cheritto', 'credit_id': '52fe4292c3a36847f8029243', 'gender': 1, 'id': 4158, 'name': 'Susan Traylor', 'order': 20, 'profile_path': '/A3ZpoAui1ure4Nx2b83wUMI8lvv.jpg'}
{'cast_id': 48, 'character': 'Schwartz', 'credit_id': '52fe4292c3a36847f8029253', 'gender': 2, 'id': 86602, 'name': 'Jerry Trimble', 'order': 21, 'profile_path': '/oDK7NCnz2z2BFV8YquEpj8PBwed.jpg'}
{'cast_id': 50, 'character': 'Albert Torena', 'credit_id': '52fe4292c3a36847f802925b', 'gender': 2, 'id': 158452, 'name': 'Ricky Harris', 'order': 22, 'profile_path': '/eJEzFSHTjGdUz1JDThdTR5C1Jrd.jpg'}
{'cast_id': 54, 'character': 'Dr. Bob', 'credit_id': '52fe4292c3a36847f802926b', 'gender': 2, 'id': 12799, 'name': 'Jeremy Piven', 'order': 23, 'profile_path': '/qtho4ZUcValnVvscTGgyWfUr4VP.jpg'}
{'cast_id': 55, 'character': 'Ralph', 'credit_id': '52fe4292c3a36847f802926f', 'gender': 2, 'id': 3982, 'name': 'Xander Berkeley', 'order': 24, 'profile_path': '/vlZ9FDMk2Xd1WHixPKxnheZoXgR.jpg'}
{'cast_id': 51, 'character': 'Anna Trejo', 'credit_id': '52fe4292c3a36847f802925f', 'gender': 1, 'id': 181343, 'name': 'Begonya Plaza', 'order': 25, 'profile_path': '/2TtFPBtz0Bd3CXAc4W5K6zF66RY.jpg'}
{'cast_id': 56, 'character': 'Armoured Guard', 'credit_id': '52fe4292c3a36847f8029273', 'gender': 2, 'id': 81687, 'name': 'Rick Avery', 'order': 26, 'profile_path': '/rXar2OrwkorJyQ9dRGf18zUEByW.jpg'}
{'cast_id': 53, 'character': 'Timmons', 'credit_id': '52fe4292c3a36847f8029267', 'gender': 2, 'id': 160970, 'name': 'Ray Buktenica', 'order': 28, 'profile_path': '/aMBLygqfsJv3QrBCvvZ7wMc3Ejq.jpg'}
{'cast_id': 59, 'character': 'Shooter at Drive-in', 'credit_id': '52fe4292c3a36847f802927f', 'gender': 0, 'id': 175600, 'name': 'Max Daniels', 'order': 29, 'profile_path': '/5zjSVtxyDExuf1913re1lG3k0Q3.jpg'}
{'cast_id': 60, 'character': 'Driver at Drive-in', 'credit_id': '52fe4292c3a36847f8029283', 'gender': 0, 'id': 12879, 'name': 'Vince Deadrick Jr.', 'order': 30, 'profile_path': '/z4HIKOQGQj8QXozFpQhj43xlmHm.jpg'}
{'cast_id': 96, 'character': 'Officer Bruce', 'credit_id': '56be773e9251417359005063', 'gender': 2, 'id': 9258, 'name': 'Steven Ford', 'order': 31, 'profile_path': '/iw8CUyekmYkGwmg0bp7foY4KvrH.jpg'}
{'cast_id': 97, 'character': 'Claudia', 'credit_id': '56be7769c3a36817f200506f', 'gender': 1, 'id': 167501, 'name': 'Farrah Forke', 'order': 32, 'profile_path': '/gmKm7TiZduyyaLlNgWnQEZHTc5Q.jpg'}
{'cast_id': 100, 'character': 'Sergeant Heinz', 'credit_id': '56be79839251417347004f69', 'gender': 2, 'id': 58535, 'name': 'Paul Herman', 'order': 34, 'profile_path': '/vaK8wxkMeKJdZEdGUufyV0Ma24M.jpg'}
{'cast_id': 101, 'character': 'Rachel', 'credit_id': '56be79cec3a36817f200511b', 'gender': 1, 'id': 161939, 'name': 'Cindy Katz', 'order': 35, 'profile_path': '/eENk49BVUS9grR2ffwEsYh9Wl69.jpg'}
{'cast_id': 102, 'character': 'Captain Jackson', 'credit_id': '56be79fa9251417344004ea0', 'gender': 0, 'id': 6580, 'name': 'Brian Libby', 'order': 36, 'profile_path': '/lvY7hpUtU12BUD8mwQqFymnsxFI.jpg'}

In [29]:
credits_df

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [155]:
cast_original = pd.read_csv('../clean_data/cast_data.csv')
cast = cast_original.copy()

Creo la columna 'movie_id' para alojar todos los id's del dataset de credits

In [121]:
cast['movie_id'] = np.nan

In [122]:
cast.loc[cast.credit_id.value_counts()]

,cast_id,character,credit_id,gender,id,name,order,profile_path,movie_id
3,28,Himself,52fe43cac3a36847f806fc33,2,1,George Lucas,3,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
3,28,Himself,52fe43cac3a36847f806fc33,2,1,George Lucas,3,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
3,28,Himself,52fe43cac3a36847f806fc33,2,1,George Lucas,3,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
3,28,Himself,52fe43cac3a36847f806fc33,2,1,George Lucas,3,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
3,28,Himself,52fe43cac3a36847f806fc33,2,1,George Lucas,3,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
...,...,...,...,...,...,...,...,...,...
1,19,Himself (voice),52fe4624c3a36847f80ef089,2,1,George Lucas,9,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
1,19,Himself (voice),52fe4624c3a36847f80ef089,2,1,George Lucas,9,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
1,19,Himself (voice),52fe4624c3a36847f80ef089,2,1,George Lucas,9,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
1,19,Himself (voice),52fe4624c3a36847f80ef089,2,1,George Lucas,9,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN
1,19,Himself (voice),52fe4624c3a36847f80ef089,2,1,George Lucas,9,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,NaN

In [146]:
cast = cast.drop_duplicates(subset='credit_id')
cast.loc[cast.credit_id == '52fe43cac3a36847f806fc33']

,cast_id,character,credit_id,gender,id,name,order,movie_id
3,28.0,Himself,52fe43cac3a36847f806fc33,2.0,1.0,George Lucas,3.0,4539.0

In [124]:
credits_df.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

Veo que hay filas duplicadas

In [125]:
credits_df.id.value_counts()

862       1
74458     1
296206    1
107308    1
16247     1
         ..
32985     1
44399     1
10138     1
32084     1
461257    1
Name: id, Length: 45432, dtype: int64

In [126]:
credits_df.loc[credits_df.id == 141971]

,cast,crew,id
13261,"[{'cast_id': 1, 'character': 'Pekka', 'credit_...","[{'credit_id': '52fe4ac89251416c750edd47', 'de...",141971

Se ve claramente que los campos de estas filas coinciden al 100%, por lo que son relamente son filas duplicadas que se pueden eliminar

In [127]:
credits_df.iloc[13261] == credits_df.iloc[13375]

cast    False
crew    False
id      False
dtype: bool

Compruebo poniendo un indice random y se ve que claramente difiere en ese caso

In [128]:
credits_df.iloc[1234] == credits_df.iloc[13375]

cast    False
crew    False
id      False
dtype: bool

Una vez visto esto, decidi borrar todos los campos que tengan duplicados el 'id' del dataset de 'credits'

In [147]:
filas_antes = credits_df.shape[0]
print('Antes: ',filas_antes)
credits_df = credits_df.drop_duplicates(subset='id')
filas_despues = credits_df.shape[0]
print('Despues: ',filas_despues)
print('Cantidad de filas eliminadas: ', filas_antes - filas_despues)

Antes:  45432
Despues:  45432
Cantidad de filas eliminadas:  0

In [130]:
credits_df.id.value_counts()

862       1
74458     1
296206    1
107308    1
16247     1
         ..
32985     1
44399     1
10138     1
32084     1
461257    1
Name: id, Length: 45432, dtype: int64

In [148]:
cast.credit_id.drop_duplicates().count()

562044

In [149]:
cast = cast.drop(columns={'profile_path'})

KeyError: "['profile_path'] not found in axis"

1

In [164]:
import time

In [175]:
time_start = time.time()
for index, value in enumerate(cast.credit_id[:1]):
    id_movie = credits_df.id.loc[credits_df.cast.str.contains(value)]
    cast.at[index, 'movie_id'] = int(id_movie)
time_finish = time.time()
duration = time_finish - time_start

In [176]:
duration

0.08220124244689941

In [181]:
cast.sort_values(by='movie_id')

,cast_id,character,credit_id,gender,id,name,order,profile_path,movie_id
27,29,Mr. Ray (voice),52fe420ec3a36847f80006d9,2,10,Bob Peterson,14,/13YNM8lBKnK26MYd2Lp3OpU6JdI.jpg,12.0
38,7,Don,52fe420fc3a36847f8000d3b,2,100,Scott Speedman,2,/hxDr3YjCYaHPEFbEfC0eXjMps0u.jpg,20.0
11,88,Missionary (uncredited),5895b352c3a36822e0004ad5,2,1,George Lucas,66,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,87.0
33,22,Michael Corvin,52fe4231c3a36847f800b0cd,2,100,Scott Speedman,1,/hxDr3YjCYaHPEFbEfC0eXjMps0u.jpg,277.0
18,5,Disappointed Man,52fe4235c3a36847f800c2f7,2,1,George Lucas,21,/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg,306.0
...,...,...,...,...,...,...,...,...,...
562469,14,Tron,59e283ed925141636000586f,0,99996,Scooter McCrae,6,None,NaN
562470,11,Boog,52fe4a279251416c750df879,0,99996,Scooter McCrae,8,None,NaN
562471,6,Dr. Radford Baines,52fe462dc3a36847f80f0ec1,2,999981,Gordon McLendon,3,None,NaN
562472,4,NaN,55f58582c3a3686d030063cf,1,999996,María Douglas,4,/y19u8s3ur4xDqLUPHQjb053HWqK.jpg,NaN
562473,1006,Father John,52fe498ec3a368484e131627,0,999999,Osvaldo Bonet,5,/5rHGjxboKrZcPwRvZXC6gX0TwDN.jpg,NaN

In [141]:
cast.loc[cast.movie_id == 42914]

,cast_id,character,credit_id,gender,id,name,order,movie_id
6661,13.0,Joseph Meister,52fe48cdc3a368484e10b9af,2.0,10165.0,Dickie Moore,11.0,42914.0
6334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42914.0

In [ ]:
original = 562044
print(f'Deberia haber {original}')
realidad = cast.movie_id.count()
print(f'Hay {realidad}')

In [ ]:
cast.movie_id.value_counts()

13611.0     1
42979.0     1
326591.0    1
4539.0      1
55676.0     1
82866.0     1
110354.0    1
57409.0     1
75311.0     1
213831.0    1
Name: movie_id, dtype: int64